In [1]:
import numpy as np

In [2]:
array = np.arange(2,11).reshape(3,3)
print(array)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [4]:
array = np.zeros(10)
array[5] = 11
print(array)

[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


In [10]:
vector = [1, 2, 0, 0, 4, 0]

cpy_vector = []

for element in vector:
    if element != 0:
        cpy_vector.append(element)
cpy_vector = np.array(cpy_vector)
print(cpy_vector)

[1 2 4]


In [14]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris = load_iris()
dt_clf = DecisionTreeClassifier()
train_data = iris.data
train_label = iris.target
dt_clf.fit(train_data, train_label)

pred = dt_clf.predict(train_data)
print("Prediction accuracy: ", accuracy_score(train_label, pred) )

Prediction accuracy:  1.0


In [18]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
from sklearn.datasets import load_iris
import numpy as np

iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)

kfold = KFold(n_splits=5)
cv_accuracy= []
print("Iris Data Set Szie:", features.shape[0])

Iris Data Set Szie: 150


In [25]:
fold_index = 0
for train_index, test_index in kfold.split(features):
    x_train, x_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    
    dt_clf.fit(x_train, y_train)
    pred = dt_clf.predict(x_test)
    fold_index += 1
    
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = x_train.shape[0]
    test_size = x_test.shape[0]
    
    print('\n#{0} fold accuracy:{1}, train size:{2}, val size:{3}'
         .format(fold_index, accuracy, train_size , test_size))
    print('\n#{0} fold accuracy:{1}'.format(fold_index, test_index))


#1 fold accuracy:1.0, train size:120, val size:30

#1 fold accuracy:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 fold accuracy:0.9667, train size:120, val size:30

#2 fold accuracy:[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 fold accuracy:0.8667, train size:120, val size:30

#3 fold accuracy:[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 fold accuracy:0.9333, train size:120, val size:30

#4 fold accuracy:[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 fold accuracy:0.7333, train size:120, val size:30

#5 fold accuracy:[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]


In [35]:
#Stratified K Fold
import pandas as pd

iris = load_iris()

df_iris = pd.DataFrame(data = iris.data, columns = iris.feature_names)
df_iris['label'] = iris.target
df_iris['label'].value_counts()

Kfold = KFold(n_splits=3)

fold_index = 0

for train_index, test_index, in kfold.split(df_iris):
    fold_index += 1
    
    label_train=df_iris['label'].iloc[train_index]
    label_test = df_iris['label'].iloc[test_index]
    
    print('## Cross validation: {0}'.format(fold_index))
    print('Train label distribution:\n', label_train.value_counts())
    print("Val label distribution:\n", label_test.value_counts())

## Cross validation: 1
Train label distribution:
 2    50
1    50
0    20
Name: label, dtype: int64
Val label distribution:
 0    30
Name: label, dtype: int64
## Cross validation: 2
Train label distribution:
 2    50
1    40
0    30
Name: label, dtype: int64
Val label distribution:
 0    20
1    10
Name: label, dtype: int64
## Cross validation: 3
Train label distribution:
 2    50
0    50
1    20
Name: label, dtype: int64
Val label distribution:
 1    30
Name: label, dtype: int64
## Cross validation: 4
Train label distribution:
 0    50
1    40
2    30
Name: label, dtype: int64
Val label distribution:
 2    20
1    10
Name: label, dtype: int64
## Cross validation: 5
Train label distribution:
 1    50
0    50
2    20
Name: label, dtype: int64
Val label distribution:
 2    30
Name: label, dtype: int64

#6 fold accuracy:1.0, train size:120, val size:30

#6 fold accuracy:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#7 fold accuracy:0.9667, t

In [32]:
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=3)
fold_index = 0

for train_index, test_index in skf.split(df_iris, df_iris['label']):
    fold_index += 1
    
    label_train = df_iris['label'].iloc[train_index]
    label_test = df_iris['label'].iloc[test_index]
    
    print('## Cross validation: .{0}'.format(fold_index))
    print('Train label distribution:\n', label_train.value_counts())
    print('Val label distribution:\n', label_test.value_counts())

## Cross validation: .1
Train label distribution:
 2    33
1    33
0    33
Name: label, dtype: int64
Val label distribution:
 2    17
1    17
0    17
Name: label, dtype: int64
## Cross validation: .2
Train label distribution:
 2    33
1    33
0    33
Name: label, dtype: int64
Val label distribution:
 2    17
1    17
0    17
Name: label, dtype: int64
## Cross validation: .3
Train label distribution:
 2    34
1    34
0    34
Name: label, dtype: int64
Val label distribution:
 2    16
1    16
0    16
Name: label, dtype: int64


In [39]:
iris = load_iris()
features = iris.data
label = iris.target

dt_clf = DecisionTreeClassifier(random_state=156)

skfold = StratifiedKFold(n_splits=3)
fold_index=0
lst_accuracy = []

for train_index, test_index in skfold.split(features, label):
    x_train, x_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    
    dt_clf.fit(x_train, y_train)
    pred = dt_clf.predict(x_test)
    fold_index += 1
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_szie = x_train.shape[0]
    test_size = x_test.shape[0]
    
    print('\n#{0} fold accuracy:{1}, train size:{2}, val size:{3}'
          .format(fold_index, accuracy, train_size , test_size))
    print('\n#{0} fold accuracy:{1}'.format(fold_index, test_index))
    
    lst_accuracy.append(accuracy)
    
print('\n##fold val accuracy:', np.round(lst_accuracy, 4))
print('##avg val accurach:', np.mean(lst_accuracy))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]

#1 fold accuracy:0.9804, train size:120, val size:51

#1 fold accuracy:[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116]

#2 fold accuracy:0.9216, train size:120, val size:51

#2 fold accuracy:[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133]

#3 fold accuracy:0.9792, train size:120, val size:48

#3 fold accuracy:[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  

In [46]:
#cross_val_score() API
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_iris

iris = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

data = iris.data
label - iris.target


scores = cross_val_score(dt_clf, data, label, scoring='accuracy', cv=3)
print('Fold val accuracy:', np.round(scores, 4))
print('Avg val accuracy:', np.round(np.mean(scores), 4))

Fold val accuracy: [0.9804 0.9216 0.9792]
Avg val accuracy: 0.9604


In [64]:
#GridSerach() API
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

iris = load_iris()
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target,
                                                   test_size=0.2, random_state=121)
dtree = DecisionTreeClassifier()

parameters = {'max_depth':[1, 2, 3], 'min_samples_split':[2, 3]}

import pandas as pd

grid_dtree = GridSearchCV(dtree, param_grid=parameters, cv=3, refit=True)

grid_dtree.fit(x_train, y_train)

scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params', 'mean_test_score', 'rank_test_score',\
          'split0_test_score', 'split1_test_score', "split2_test_score"]]

print(scores_df)

print('Optimal parameter:', grid_dtree.best_params_)
print('Max accuracy: {0:.4f}'.format(grid_dtree.best_score_))

estimator = grid_dtree.best_estimator_

pred = estimator.predict(x_test)
print('Test dataset accuracy: {0:.4f}'.format(accuracy_score(y_test, pred)))

   mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.000355      0.000064  ...        0.000000                5
1       0.000331      0.000029  ...        0.000000                5
2       0.000348      0.000020  ...        0.031180                3
3       0.000678      0.000076  ...        0.031180                3
4       0.000462      0.000049  ...        0.020412                1
5       0.000415      0.000060  ...        0.020412                1

[6 rows x 13 columns]
Optimal parameter: {'max_depth': 3, 'min_samples_split': 2}
Max accuracy: 0.9750
Test dataset accuracy: 0.9667
